# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 531ac5a0f89d9e744afa8740d6f05294cff6ae750853c33dac3dac5fb1ff0678a243bfd107dd05c305f1e86a4baeaa6a32b972ebb15755fb14c4ec121bb8e7c2

test:
  secret_key_base: 1c540e05f8133bf42019ba1e973b0a9fc62b5f82c2dcdd854a78c5300851212961a1449bb7343a2c21aee85c6021d7978d6d7043361ae4d3c1f3d66b1019518c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
